package org.example

import com.google.gson.FieldNamingPolicy
import com.google.gson.GsonBuilder
import com.google.gson.TypeAdapter
import com.google.gson.stream.JsonReader
import com.google.gson.stream.JsonWriter
import java.time.LocalDateTime
import java.time.format.DateTimeFormatter

enum class NDCRequestCode {
    // request below used by the payment processor
    EARMARK_REQUESTED,
    EARMARK_COMMIT,
    EARMARK_RELEASE,

    // the messages are control messaged used by the operator
    PP_DISABLE,
    PP_ENABLE,
    PP_EARMARK_TOP_UP,
    PP_ONBOARD,
    SETTLEMENT_ROLLOVER,

    // QUERY functions
    QUERY_POSITION,
    QUERY_SETTLEMENT,
    QUERY_PP_STATUS,
}

class LocalDateTimeAdapter : TypeAdapter<LocalDateTime>() {
    private val formatter: DateTimeFormatter = DateTimeFormatter.ISO_LOCAL_DATE_TIME

    /**
     * Serializes a LocalDateTime object to a JSON string
     * The output will be a string in ISO 8601 format (e.g. "2025-09-12T16:14:00")
     */
    override fun write(out: JsonWriter, value: LocalDateTime?) {
        if (value == null) {
            out.nullValue()
        } else {
            out.value(value.format(formatter))
        }
    }

    /**
     * Deserializes a JSON string back into a LocalDateTime object
     */
    override fun read(reader: JsonReader): LocalDateTime? {
        val value = reader.nextString()
        return if (value.isNullOrEmpty()) {
            null
        } else {
            LocalDateTime.parse(value, formatter)
        }
    }
}

val rootGson = GsonBuilder()
    .setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)
    .registerTypeAdapter(LocalDateTime::class.java, LocalDateTimeAdapter())
    .create()

data class NDCRequest(
    val bankId: Int, // Payment Processor that created this request, this will be the debitBankId
    val bankGES: Long, // maps to the internal sequence generated by the PP
    val debitBankId: Int, // origin of Funds
    val creditBankId: Int, // destination of Funds
    val requestCode: NDCRequestCode, // what is being requested
) {
    var earmarkInCents: Int = -1
    var ndcGES: Long = -1 // used when requesting a earmark release / commit
    var netSettlementId: Int? = null // used to enquire the settlement position

    // only used by the OnBoard process to create the settlement_account
    var ndcAccountNumber: String? = null
    fun toJson(): String {
        return rootGson.toJson(this)
    }
}

fun main() {
    val request = NDCRequest(
        1,
        1,
        -1,
        2,
        NDCRequestCode.QUERY_POSITION
    ).apply {
        netSettlementId = 2107213454
    }

    val requestBody = rootGson.toJson(request)
    println(requestBody)
}